# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [2]:
#IMPORT PANDAS TOOLS
import pandas as pd

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [6]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(10)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65
4,AFG,1994,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65
5,AFG,1995,0.159,NaN,NaN,0.843,0.912,0.000,0.069,-1.65
6,AFG,1996,0.062,NaN,NaN,0.745,0.906,0.000,0.029,-1.65
7,AFG,1997,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65
8,AFG,1998,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65
9,AFG,1999,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65

In [10]:
democracy_gdp.country.unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [7]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(10)

            Country  year     emissions
11438  GLOBAL TOTAL  2014  48930.176837
11439  GLOBAL TOTAL  2015  48808.767176
11440  GLOBAL TOTAL  2016  49058.441256
11441  GLOBAL TOTAL  2017  49878.733809
11442  GLOBAL TOTAL  2018  51026.627449
11443  GLOBAL TOTAL  2019  51278.347920
11444  GLOBAL TOTAL  2020  49327.538885
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [9]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [13]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['JPN', 'CHN', 'KOR'],
)
gdp_data.head(10)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),China,CHN,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),China,CHN,2024,13303.148154,NaN,NaN,1
2,GDP per capita (current US$),China,CHN,2023,12951.178240,NaN,NaN,1
3,GDP per capita (current US$),China,CHN,2022,12970.605641,NaN,NaN,1
4,GDP per capita (current US$),China,CHN,2021,12887.435724,NaN,NaN,1
5,GDP per capita (current US$),China,CHN,2020,10627.463799,NaN,NaN,1
6,GDP per capita (current US$),China,CHN,2019,10342.900952,NaN,NaN,1
7,GDP per capita (current US$),China,CHN,2018,10085.663815,NaN,NaN,1
8,GDP per capita (current US$),China,CHN,2017,8979.676527,NaN,NaN,1
9,GDP per capita (current US$),China,CHN,2016,8254.868593,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [28]:
population_indicator = 'SP.POP.TOTL'



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(10)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
278,"Population, total",United States,USA,1999,279040000.0,NaN,NaN,0
279,"Population, total",United States,USA,1998,275854000.0,NaN,NaN,0
280,"Population, total",United States,USA,1997,272657000.0,NaN,NaN,0
281,"Population, total",United States,USA,1996,269394000.0,NaN,NaN,0
282,"Population, total",United States,USA,1995,266278000.0,NaN,NaN,0
283,"Population, total",United States,USA,1994,263126000.0,NaN,NaN,0
284,"Population, total",United States,USA,1993,259919000.0,NaN,NaN,0
285,"Population, total",United States,USA,1992,256514000.0,NaN,NaN,0
286,"Population, total",United States,USA,1991,252981000.0,NaN,NaN,0
287,"Population, total",United States,USA,1990,249623000.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [31]:
democracy_gdp.country.head(10)

0    AFG
1    AFG
2    AFG
3    AFG
4    AFG
5    AFG
6    AFG
7    AFG
8    AFG
9    AFG
Name: country, dtype: object

## 2.2 Filter Rows

Filter rows based on conditions.

In [32]:
# Show unique values in a column
democracy_gdp.country.unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [34]:
# Filter using query

democracy_gdp.query("country == 'JPN' & year > 2000").head(10)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
396,JPN,2001,0.902,NaN,NaN,0.037,0.1,0.920,0.934,1.809
397,JPN,2002,0.902,NaN,NaN,0.037,0.1,0.920,0.934,1.809
398,JPN,2003,0.902,NaN,NaN,0.037,0.1,0.921,0.934,1.809
399,JPN,2004,0.905,NaN,NaN,0.037,0.1,0.923,0.934,1.809
400,JPN,2005,0.906,NaN,NaN,0.037,0.1,0.927,0.934,1.809
401,JPN,2006,0.908,NaN,NaN,0.037,0.1,0.934,0.934,1.809
402,JPN,2007,0.908,NaN,NaN,0.037,0.1,0.934,0.934,1.809
403,JPN,2008,0.909,NaN,NaN,0.037,0.1,0.934,0.934,1.973
404,JPN,2009,0.915,NaN,NaN,0.037,0.1,0.934,0.938,1.973
405,JPN,2010,0.915,NaN,NaN,0.037,0.1,0.933,0.938,1.816

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [36]:
# Filter with multiple conditions

democracy_gdp.query("year > 2000 & year < 2010").head(10)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
11,AFG,2001,0.081,NaN,NaN,0.747,0.806,0.000,0.049,-1.650
12,AFG,2002,0.642,NaN,NaN,0.892,0.910,0.000,0.547,-0.896
13,AFG,2003,0.642,NaN,NaN,0.892,0.910,0.000,0.612,-0.896
14,AFG,2004,0.652,NaN,NaN,0.892,0.934,0.060,0.600,-0.896
15,AFG,2005,0.648,NaN,NaN,0.929,0.927,0.241,0.625,-0.813
16,AFG,2006,0.648,NaN,NaN,0.938,0.941,0.241,0.621,-0.750
17,AFG,2007,0.648,NaN,NaN,0.942,0.945,0.241,0.622,-0.750
18,AFG,2008,0.652,NaN,NaN,0.942,0.945,0.241,0.629,-0.750
19,AFG,2009,0.650,NaN,NaN,0.942,0.945,0.215,0.631,-0.750
46,ARM,2001,0.732,NaN,NaN,0.780,0.863,0.355,0.681,1.008

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [51]:
# Filter Multiple and show unique countries
# You can either do one or two lines

democracy_gdp.query("country == ['JPN', 'KOR', 'IND']").head(10)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
350,IND,1990,0.800,NaN,NaN,0.374,0.548,0.789,0.814,0.768
351,IND,1991,0.811,NaN,NaN,0.374,0.548,0.820,0.814,1.539
352,IND,1992,0.815,NaN,NaN,0.585,0.548,0.829,0.814,1.539
353,IND,1993,0.822,NaN,NaN,0.585,0.548,0.829,0.814,1.539
354,IND,1994,0.822,NaN,NaN,0.585,0.548,0.829,0.814,1.539
355,IND,1995,0.822,NaN,NaN,0.585,0.548,0.829,0.814,1.539
356,IND,1996,0.814,NaN,NaN,0.585,0.548,0.847,0.814,1.539
357,IND,1997,0.810,NaN,NaN,0.585,0.548,0.856,0.814,1.539
358,IND,1998,0.820,NaN,NaN,0.585,0.548,0.857,0.814,1.539
359,IND,1999,0.809,NaN,NaN,0.585,0.548,0.857,0.801,1.539

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [49]:
# Filter rows and select columns

democracy_gdp.query("country == ['KOR']")[['country', 'year', 'v2x_pubcorr']].head(10)

    country  year  v2x_pubcorr
525     KOR  1990        0.339
526     KOR  1990        0.339
527     KOR  1990        0.339
528     KOR  1990        0.339
529     KOR  1990        0.339
530     KOR  1990        0.339
531     KOR  1990        0.339
532     KOR  1990        0.339
533     KOR  1990        0.339
534     KOR  1990        0.339

## 2.6 Rename Columns

Rename columns in the dataframe.

In [52]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [56]:
# Rename using rename with axis parameter

democracy_gdp.rename({"v2x_frassoc_thick": "something_idk"}, axis = 1).head(10)

,country,year,something_idk,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65
4,AFG,1994,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65
5,AFG,1995,0.159,NaN,NaN,0.843,0.912,0.000,0.069,-1.65
6,AFG,1996,0.062,NaN,NaN,0.745,0.906,0.000,0.029,-1.65
7,AFG,1997,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65
8,AFG,1998,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65
9,AFG,1999,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.65