# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [1]:
#IMPORT PANDAS TOOLS
import pandas as pd

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [4]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.tail(3)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
5597,VNM,2022,0.025,NaN,NaN,0.517,0.372,0.531,0.186,1.977
5598,VNM,2023,0.021,NaN,NaN,0.517,0.364,0.513,0.187,1.571
5599,VNM,2024,0.021,NaN,NaN,0.477,0.364,0.514,0.176,1.963

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [5]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [23]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [26]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= {"JP","CA"},
    #Why do I need the {} here?
)
gdp_data.tail(5)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
67,GDP per capita (current US$),Japan,JPN,1994,39933.515056,NaN,NaN,1
68,GDP per capita (current US$),Japan,JPN,1993,36345.244126,NaN,NaN,1
69,GDP per capita (current US$),Japan,JPN,1992,31992.790212,NaN,NaN,1
70,GDP per capita (current US$),Japan,JPN,1991,29428.428904,NaN,NaN,1
71,GDP per capita (current US$),Japan,JPN,1990,25801.395039,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [22]:
population_indicator = 'NY.GDP.PCAP.CD'



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,GDP per capita (current US$),United States,USA,1992,25418.990776,NaN,NaN,1
286,GDP per capita (current US$),United States,USA,1991,24342.258905,NaN,NaN,1
287,GDP per capita (current US$),United States,USA,1990,23888.600009,NaN,NaN,1

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [37]:
import pandas as pd
df = pd.read_csv(democracy_gdp_filepath)
df.head(3)[['country','year']]

  country  year
0     AFG  1990
1     AFG  1991
2     AFG  1992

## 2.2 Filter Rows

Filter rows based on conditions.

In [45]:
# Show unique values in a column
#YOUR CODE HERE
df.country.unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [ ]:
# Filter using query

#YOUR CODE HERE
df.query("country == 'AFG'")
#when to use '', when to use""?

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.650
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.650
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.650
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
4,AFG,1994,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
5,AFG,1995,0.159,NaN,NaN,0.843,0.912,0.000,0.069,-1.650
6,AFG,1996,0.062,NaN,NaN,0.745,0.906,0.000,0.029,-1.650
7,AFG,1997,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.650
8,AFG,1998,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.650
9,AFG,1999,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.650
10,AFG,2000,0.038,NaN,NaN,0.707,0.806,0.000,0.020,-1.650
11,AFG,2001,0.081,NaN,NaN,0.747,0.806,0.000,0.049,-1.650
12,AFG,2002,0.642,NaN,NaN,0.892,0.910,0.000,0.547,-0.896
13,AFG,2003,0.642,NaN,NaN,0.892,0.910,0.000,0.612,-0.896
14,AFG,2004,0.652,NaN,NaN,0.892,0.934,0.060,0.600,-0.896
15,AFG,2005,0.648,NaN,NaN,0.929,0.927,0.241,0.625,-0.813
16,AFG,2006,0.648,NaN,NaN,0.938,0.941,0.241,0.621,-0.750
17,AFG,2007,0.648,NaN,NaN,0.942,0.945,0.241,0.622,-0.750
18,AFG,2008,0.652,NaN,NaN,0.942,0.945,0.241,0.629,-0.750
19,AFG,2009,0.650,NaN,NaN,0.942,0.945,0.215,0.631,-0.750
20,AFG,2010,0.629,NaN,NaN,0.951,0.945,0.175,0.638,-0.750
21,AFG,2011,0.632,NaN,NaN,0.951,0.945,0.186,0.638,-0.750
22,AFG,2012,0.635,NaN,NaN,0.960,0.945,0.195,0.639,-0.792
23,AFG,2013,0.625,NaN,NaN,0.928,0.923,0.193,0.625,-0.423
24,AFG,2014,0.625,NaN,NaN,0.900,0.911,0.195,0.627,-0.423
25,AFG,2015,0.611,NaN,NaN,0.894,0.867,0.196,0.608,-0.423
26,AFG,2016,0.597,NaN,NaN,0.882,0.879,0.184,0.590,-0.943
27,AFG,2017,0.584,NaN,NaN,0.866,0.871,0.168,0.602,-1.386
28,AFG,2018,0.580,NaN,NaN,0.825,0.892,0.165,0.615,-1.386
29,AFG,2019,0.605,NaN,NaN,0.842,0.898,0.156,0.573,-0.949
30,AFG,2020,0.566,NaN,NaN,0.818,0.849,0.161,0.613,-0.673
31,AFG,2021,0.096,NaN,NaN,0.523,0.681,0.063,0.103,-2.552
32,AFG,2022,0.035,NaN,NaN,0.585,0.571,0.000,0.031,-3.141
33,AFG,2023,0.027,NaN,NaN,0.567,0.651,0.000,0.026,-3.141
34,AFG,2024,0.050,NaN,NaN,0.680,0.678,0.000,0.053,-3.141

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [46]:
# Filter with multiple conditions

#YOUR CODE HERE
df.query("country == 'CHN' & year > 2021")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
242,CHN,2022,0.043,NaN,NaN,0.483,0.491,0.0,0.050,0.926
243,CHN,2023,0.036,NaN,NaN,0.498,0.525,0.0,0.046,0.926
244,CHN,2024,0.036,NaN,NaN,0.498,0.556,0.0,0.048,1.082

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [50]:
# Filter Multiple and show unique countries
# You can either do one or two lines

#YOUR CODE HERE
df.query("country == 'CHN' | year > 2020")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
31,AFG,2021,0.096,NaN,NaN,0.523,0.681,0.063,0.103,-2.552
32,AFG,2022,0.035,NaN,NaN,0.585,0.571,0.000,0.031,-3.141
33,AFG,2023,0.027,NaN,NaN,0.567,0.651,0.000,0.026,-3.141
34,AFG,2024,0.050,NaN,NaN,0.680,0.678,0.000,0.053,-3.141
66,ARM,2021,0.876,NaN,NaN,0.264,0.337,0.813,0.797,2.239
...,...,...,...,...,...,...,...,...,...,...
5564,UZB,2024,0.143,NaN,NaN,0.806,0.819,0.299,0.266,1.355
5596,VNM,2021,0.042,NaN,NaN,0.517,0.390,0.526,0.177,1.977
5597,VNM,2022,0.025,NaN,NaN,0.517,0.372,0.531,0.186,1.977
5598,VNM,2023,0.021,NaN,NaN,0.517,0.364,0.513,0.187,1.571
5599,VNM,2024,0.021,NaN,NaN,0.477,0.364,0.514,0.176,1.963

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [54]:
# Filter rows and select columns

#YOUR CODE HERE
short_data = df.query("year > 2022 & country == 'JPN'")[['country', 'year', 'NGDPDPC','v2x_pubcorr']]
short_data.head(4)

    country  year  NGDPDPC  v2x_pubcorr
418     JPN  2023      NaN        0.037
419     JPN  2024      NaN        0.037

## 2.6 Rename Columns

Rename columns in the dataframe.

In [ ]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [ ]:
# Rename using rename with axis parameter

#YOUR CODE HERE
df.rename({"year" : "date"}, axis=1).head(2)
#what does axis=1 mean?

,country,date,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65