# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [27]:
#IMPORT PANDAS TOOLS
import pandas as pd

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [28]:
democracy_gdp_filepath = "C:/Users/laure/Documents/DataScience/datascience-publicpolicy-2026/data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [29]:
ghg_file_path = "C:/Users/laure/Documents/DataScience/datascience-publicpolicy-2026/data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [30]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [31]:
!pip install lxml
!pip install plotly
!pip install altair

Requirement already satisfied: lxml in C:\Users\laure\miniconda3\Lib\site-packages (6.1.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: plotly in C:\Users\laure\miniconda3\Lib\site-packages (6.7.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\laure\miniconda3\Lib\site-packages (from plotly) (2.12.0)
Requirement already satisfied: packaging in C:\Users\laure\miniconda3\Lib\site-packages (from plotly) (25.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: altair in C:\Users\laure\miniconda3\Lib\site-packages (6.0.0)
Requirement already satisfied: jinja2 in C:\Users\laure\miniconda3\Lib\site-packages (from altair) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in C:\Users\laure\miniconda3\Lib\site-packages (from altair) (4.26.0)
Requirement already satisfied: narwhals>=1.27.1 in C:\Users\laure\miniconda3\Lib\site-packages (from altair) (2.12.0)
Requirement already satisfied: packaging in C:\Users\laure\miniconda3\Lib\site-packages (from altair) (25.0)
Requirement already satisfied: typing-extensions>=4.12.0 in C:\Users\laure\miniconda3\Lib\site-packages (from altair) (4.15.0)
Requirement already satisfied: attrs>=22.2.0 in C:\Users\laure\miniconda3\Lib\site-packages (from jsonschema>=3.0->altair) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in C:\Users\laure\miniconda3\Lib\site-packages (from jsonschema>=3.0->altair) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in C:\Users\laure\miniconda3\Lib\site-packages (from jsonschema>=3.0->altair) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in C:\Users\laure\miniconda3\Lib\site-packages (from jsonschema>=3.0->altair) (0.30.0)
Requirement already satisfied: MarkupSafe>=2.0 in C:\Users\laure\miniconda3\Lib\site-packages (from jinja2->altair) (3.0.2)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
gdp_data = download_worldbank(indicator='NY.GDP.PCAP.CD', 
                                date_start= 1990, 
                                date_end= 2026,
                                countries= ["FR"])
gdp_data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),France,FRA,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),France,FRA,2024,46103.084086,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [33]:
population_indicator = 'SP.POP.TOTL'



country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.head(15)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,"Population, total",Australia,AUS,2025,NaN,NaN,NaN,0
1,"Population, total",Australia,AUS,2024,27196812.0,NaN,NaN,0
2,"Population, total",Australia,AUS,2023,26659922.0,NaN,NaN,0
3,"Population, total",Australia,AUS,2022,26018721.0,NaN,NaN,0
4,"Population, total",Australia,AUS,2021,25685412.0,NaN,NaN,0
5,"Population, total",Australia,AUS,2020,25649248.0,NaN,NaN,0
6,"Population, total",Australia,AUS,2019,25334826.0,NaN,NaN,0
7,"Population, total",Australia,AUS,2018,24963258.0,NaN,NaN,0
8,"Population, total",Australia,AUS,2017,24592588.0,NaN,NaN,0
9,"Population, total",Australia,AUS,2016,24190907.0,NaN,NaN,0
10,"Population, total",Australia,AUS,2015,23815995.0,NaN,NaN,0
11,"Population, total",Australia,AUS,2014,23475686.0,NaN,NaN,0
12,"Population, total",Australia,AUS,2013,23128129.0,NaN,NaN,0
13,"Population, total",Australia,AUS,2012,22733465.0,NaN,NaN,0
14,"Population, total",Australia,AUS,2011,22340024.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [34]:
democracy_gdp.columns

Index(['country', 'year', 'v2x_frassoc_thick', 'NGDPDPC', 'NGDP_RPCH',
       'v2x_pubcorr', 'v2xnp_regcorr', 'v2xel_frefair', 'v2x_freexp',
       'v2elembcap'],
      dtype='object')

In [35]:
selected = democracy_gdp[['country','year','v2xel_frefair']]
selected

     country  year  v2xel_frefair
0        AFG  1990          0.069
1        AFG  1991          0.069
2        AFG  1992          0.028
3        AFG  1993          0.000
4        AFG  1994          0.000
...      ...   ...            ...
5595     VNM  2020          0.495
5596     VNM  2021          0.526
5597     VNM  2022          0.531
5598     VNM  2023          0.513
5599     VNM  2024          0.514

[5600 rows x 3 columns]

## 2.2 Filter Rows

Filter rows based on conditions.

In [36]:
# Show unique values in a column - column country in df selected
unique_countries = selected['country'].unique()
unique_countries

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [37]:
# Filter using query
filtered = democracy_gdp.query("country == 'JPN'")
filtered.head()

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
388,JPN,1993,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
389,JPN,1994,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [38]:
# Filter with multiple conditions

filtereded = democracy_gdp.query("country == 'JPN'  and year > 2000")
filtereded

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
396,JPN,2001,0.902,NaN,NaN,0.037,0.100,0.920,0.934,1.809
397,JPN,2002,0.902,NaN,NaN,0.037,0.100,0.920,0.934,1.809
398,JPN,2003,0.902,NaN,NaN,0.037,0.100,0.921,0.934,1.809
399,JPN,2004,0.905,NaN,NaN,0.037,0.100,0.923,0.934,1.809
400,JPN,2005,0.906,NaN,NaN,0.037,0.100,0.927,0.934,1.809
401,JPN,2006,0.908,NaN,NaN,0.037,0.100,0.934,0.934,1.809
402,JPN,2007,0.908,NaN,NaN,0.037,0.100,0.934,0.934,1.809
403,JPN,2008,0.909,NaN,NaN,0.037,0.100,0.934,0.934,1.973
404,JPN,2009,0.915,NaN,NaN,0.037,0.100,0.934,0.938,1.973
405,JPN,2010,0.915,NaN,NaN,0.037,0.100,0.933,0.938,1.816
406,JPN,2011,0.915,NaN,NaN,0.037,0.100,0.933,0.938,1.816
407,JPN,2012,0.907,NaN,NaN,0.037,0.100,0.933,0.936,1.816
408,JPN,2013,0.909,NaN,NaN,0.037,0.100,0.931,0.883,1.816
409,JPN,2014,0.909,NaN,NaN,0.037,0.100,0.931,0.883,1.816
410,JPN,2015,0.911,NaN,NaN,0.037,0.078,0.931,0.883,1.816
411,JPN,2016,0.911,NaN,NaN,0.037,0.116,0.931,0.883,1.816
412,JPN,2017,0.911,NaN,NaN,0.037,0.107,0.933,0.883,1.816
413,JPN,2018,0.933,NaN,NaN,0.037,0.107,0.946,0.874,2.009
414,JPN,2019,0.930,NaN,NaN,0.037,0.107,0.946,0.871,2.009
415,JPN,2020,0.930,NaN,NaN,0.037,0.107,0.943,0.876,1.919
416,JPN,2021,0.929,NaN,NaN,0.037,0.094,0.943,0.859,1.919
417,JPN,2022,0.927,NaN,NaN,0.037,0.094,0.938,0.865,1.919
418,JPN,2023,0.927,NaN,NaN,0.037,0.092,0.938,0.866,1.919
419,JPN,2024,0.927,NaN,NaN,0.037,0.092,0.934,0.865,1.676

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [39]:
target_countries = ['JPN', 'KOR']
filtered_df = democracy_gdp[democracy_gdp['country'].isin(target_countries)]
filtered_df

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
388,JPN,1993,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
389,JPN,1994,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
...,...,...,...,...,...,...,...,...,...,...
2760,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2761,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2762,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2763,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535
2764,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [40]:
# Filter rows and select columns

filtered_df = democracy_gdp.loc[
    (democracy_gdp['country'].isin(target_countries)) & (democracy_gdp['year'] > 2000), 
    ['country', 'year', 'NGDPDPC']
]
filtered_df

     country  year    NGDPDPC
396      JPN  2001        NaN
397      JPN  2002        NaN
398      JPN  2003        NaN
399      JPN  2004        NaN
400      JPN  2005        NaN
...      ...   ...        ...
2760     KOR  2024  36128.987
2761     KOR  2024  36128.987
2762     KOR  2024  36128.987
2763     KOR  2024  36128.987
2764     KOR  2024  36128.987

[1560 rows x 3 columns]

## 2.6 Rename Columns

Rename columns in the dataframe.

In [41]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [42]:
# Rename using rename with axis parameter

democracy_gdp = democracy_gdp.rename(columns={"country": "country_code"})