# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [ ]:
#IMPORT PANDAS TOOLS
import pandas as pd
saveddata = pd.read_csv("../../data/hw/democracy_gdp.csv")
#saveddata
#Comment for a random change you can delete later

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [59]:
file_location = ("../../data/hw/democracy_gdp.csv")
df = pd.read_csv(file_location)
df

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.650
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.650
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.650
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
4,AFG,1994,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.650
...,...,...,...,...,...,...,...,...,...,...
5595,VNM,2020,0.044,NaN,NaN,0.489,0.373,0.495,0.206,1.255
5596,VNM,2021,0.042,NaN,NaN,0.517,0.390,0.526,0.177,1.977
5597,VNM,2022,0.025,NaN,NaN,0.517,0.372,0.531,0.186,1.977
5598,VNM,2023,0.021,NaN,NaN,0.517,0.364,0.513,0.187,1.571
5599,VNM,2024,0.021,NaN,NaN,0.477,0.364,0.514,0.176,1.963

In [60]:
df.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [61]:
file_location2 = ("../../data/hw/ghg.csv")
df2 = pd.read_csv(file_location2)
df2

            Country  year     emissions
0             Aruba  1970      0.036713
1             Aruba  1971      0.041538
2             Aruba  1972      0.052391
3             Aruba  1973      0.057360
4             Aruba  1974      0.056630
...             ...   ...           ...
11443  GLOBAL TOTAL  2019  51278.347920
11444  GLOBAL TOTAL  2020  49327.538885
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

[11448 rows x 3 columns]

In [62]:
df2.tail(4)

            Country  year     emissions
11444  GLOBAL TOTAL  2020  49327.538885
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [63]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [41]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries=  ["US", "JP", "CN"]
)
gdp_data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),China,CHN,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),China,CHN,2024,13303.148154,NaN,NaN,1

In [51]:
df.info

<bound method DataFrame.info of      country  year  v2x_frassoc_thick  NGDPDPC  NGDP_RPCH  v2x_pubcorr  \
0        AFG  1990              0.063      NaN        NaN        0.556
1        AFG  1991              0.068      NaN        NaN        0.556
2        AFG  1992              0.134      NaN        NaN        0.645
3        AFG  1993              0.159      NaN        NaN        0.843
4        AFG  1994              0.159      NaN        NaN        0.843
...      ...   ...                ...      ...        ...          ...
5595     VNM  2020              0.044      NaN        NaN        0.489
5596     VNM  2021              0.042      NaN        NaN        0.517
5597     VNM  2022              0.025      NaN        NaN        0.517
5598     VNM  2023              0.021      NaN        NaN        0.517
5599     VNM  2024              0.021      NaN        NaN        0.477

      v2xnp_regcorr  v2xel_frefair  v2x_freexp  v2elembcap
0             0.538          0.069       0.085      -1.650
1             0.538          0.069       0.074      -1.650
2             0.736          0.028       0.071      -1.650
3             0.909          0.000       0.069      -1.650
4             0.909          0.000       0.069      -1.650
...             ...            ...         ...         ...
5595          0.373          0.495       0.206       1.255
5596          0.390          0.526       0.177       1.977
5597          0.372          0.531       0.186       1.977
5598          0.364          0.513       0.187       1.571
5599          0.364          0.514       0.176       1.963

[5600 rows x 10 columns]>

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [55]:
population_indicator = df



country_list = ["USA", "JP", "CN"]

pop_data = download_worldbank(df
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1866569527.py, line 7)

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [58]:
short_data = df("date > 2021 &")[['country', 'date', 'value']]
short_data.head(3)

TypeError: 'DataFrame' object is not callable

In [ ]:
#YOUR CODE HERE

0    AFG
1    AFG
2    AFG
3    AFG
4    AFG
Name: country, dtype: object

## 2.2 Filter Rows

Filter rows based on conditions.

In [ ]:
# Show unique values in a column
#YOUR CODE HERE

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [56]:
# Filter using query

#YOUR CODE HERE

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [57]:
# Filter with multiple conditions

#YOUR CODE HERE

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [ ]:
# Filter Multiple and show unique countries
# You can either do one or two lines

#YOUR CODE HERE

array(['JPN', 'KOR'], dtype=object)

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [ ]:
# Filter rows and select columns

#YOUR CODE HERE

    country  year  NGDPDPC  v2x_pubcorr
417     JPN  2022      NaN        0.037
418     JPN  2023      NaN        0.037
419     JPN  2024      NaN        0.037

## 2.6 Rename Columns

Rename columns in the dataframe.

In [ ]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [ ]:
# Rename using rename with axis parameter

#YOUR CODE HERE

  country  date
0     AFG  1990
1     AFG  1991