# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [ ]:
#IMPORT PANDAS TOOLS
import pandas as pd
saveddata= pd.read_csv("../../data/hw/democracy_gdp.csv")

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [6]:
democracy_gdp_filepath = ("../../data/hw/democracy_gdp.csv")
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [7]:
ghg_file_path = ("../../data/hw/ghg.csv")
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [8]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [28]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['IT' ]
)
gdp_data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),Italy,ITA,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),Italy,ITA,2024,40385.341396,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [33]:
population_indicator = 'NY.GDP.PCAP.CD'


country_list = [
    "USA",  # United States of America
    "CAN",  # Canada
    "MEX",  # Mexico
    "GBR",  # United Kingdom of Great Britain and Northern Ireland
    "FRA",  # France
    "DEU",  # Germany (Deutschland)
    "JPN",  # Japan
    "AUS"   # Australia
]


pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
285,GDP per capita (current US$),United States,USA,1992,25418.990776,NaN,NaN,1
286,GDP per capita (current US$),United States,USA,1991,24342.258905,NaN,NaN,1
287,GDP per capita (current US$),United States,USA,1990,23888.600009,NaN,NaN,1

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [43]:
df = pd.read_csv ("../../data/hw/democracy_gdp.csv")

In [44]:
df['country']

0       AFG
1       AFG
2       AFG
3       AFG
4       AFG
       ...
5595    VNM
5596    VNM
5597    VNM
5598    VNM
5599    VNM
Name: country, Length: 5600, dtype: object

## 2.2 Filter Rows

Filter rows based on conditions.

In [45]:
df.country.unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [73]:
df.query("country == 'JPN' "). head (3)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [9]:
result = df[(df['country'] == 'KOR') & (df['year'] == 2024)]

print(result)

     country  year  v2x_frassoc_thick    NGDPDPC  NGDP_RPCH  v2x_pubcorr  \
2701     KOR  2024              0.817  36128.987        2.0        0.167
2702     KOR  2024              0.817  36128.987        2.0        0.167
2703     KOR  2024              0.817  36128.987        2.0        0.167
2704     KOR  2024              0.817  36128.987        2.0        0.167
2705     KOR  2024              0.817  36128.987        2.0        0.167
...      ...   ...                ...        ...        ...          ...
2760     KOR  2024              0.817  36128.987        2.0        0.167
2761     KOR  2024              0.817  36128.987        2.0        0.167
2762     KOR  2024              0.817  36128.987        2.0        0.167
2763     KOR  2024              0.817  36128.987        2.0        0.167
2764     KOR  2024              0.817  36128.987        2.0        0.167

      v2xnp_regcorr  v2xel_frefair  v2x_freexp  v2elembcap
2701          0.094          0.932       0.756       2.535
2702          0.094          0.932       0.756       2.535
2703          0.094          0.932       0.756       2.535
2704          0.094          0.932       0.756       2.535
2705          0.094          0.932       0.756       2.535
...             ...            ...         ...         ...
2760          0.094          0.932       0.756       2.535
2761          0.094          0.932       0.756       2.535
2762          0.094          0.932       0.756       2.535
2763          0.094          0.932       0.756       2.535
2764          0.094          0.932       0.756       2.535

[64 rows x 10 columns]

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [7]:
filtered_countries = df[df['country'].isin(['JPN', 'KOR'])]['country'].unique()

print(filtered_countries)

['JPN' 'KOR']

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [8]:
result = df.loc[df['country'] == 'JPN', ['country', 'year', 'NGDPDPC', 'v2x_pubcorr']]

print(result)

    country  year  NGDPDPC  v2x_pubcorr
385     JPN  1990      NaN        0.048
386     JPN  1991      NaN        0.048
387     JPN  1992      NaN        0.048
388     JPN  1993      NaN        0.048
389     JPN  1994      NaN        0.048
390     JPN  1995      NaN        0.048
391     JPN  1996      NaN        0.048
392     JPN  1997      NaN        0.048
393     JPN  1998      NaN        0.037
394     JPN  1999      NaN        0.037
395     JPN  2000      NaN        0.037
396     JPN  2001      NaN        0.037
397     JPN  2002      NaN        0.037
398     JPN  2003      NaN        0.037
399     JPN  2004      NaN        0.037
400     JPN  2005      NaN        0.037
401     JPN  2006      NaN        0.037
402     JPN  2007      NaN        0.037
403     JPN  2008      NaN        0.037
404     JPN  2009      NaN        0.037
405     JPN  2010      NaN        0.037
406     JPN  2011      NaN        0.037
407     JPN  2012      NaN        0.037
408     JPN  2013      NaN        0.037
409     JPN  2014      NaN        0.037
410     JPN  2015      NaN        0.037
411     JPN  2016      NaN        0.037
412     JPN  2017      NaN        0.037
413     JPN  2018      NaN        0.037
414     JPN  2019      NaN        0.037
415     JPN  2020      NaN        0.037
416     JPN  2021      NaN        0.037
417     JPN  2022      NaN        0.037
418     JPN  2023      NaN        0.037
419     JPN  2024      NaN        0.037

## 2.6 Rename Columns

Rename columns in the dataframe.

In [ ]:
# Before rename
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [72]:
rename_dictionary = {"year": "date"}
df.rename (rename_dictionary, axis=1).head(2)
#df = copyright
#copyright.rename (rename_country_map, axis=1)

,country,date,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65