# Homework 1: Data Reading & Manipulation

In this homework, you will practice:
1. Reading data from CSV files and APIs
2. Data manipulation techniques covered in Week 2

# Section 1: Reading Data

## 1.1 Reading CSV Files

##### IMPORTANT: We will read data from the `data/hw/` folder so you need to remember to go back two folders to access data

In [18]:
#IMPORT PANDAS TOOLS
import pandas as pd

### 1.1.1 GDP and Democracy Data

Load the `democracy_gdp.csv` file.

In [20]:
democracy_gdp_filepath = "../../data/hw/democracy_gdp.csv"
democracy_gdp = pd.read_csv(democracy_gdp_filepath)
democracy_gdp.head(4)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65
2,AFG,1992,0.134,NaN,NaN,0.645,0.736,0.028,0.071,-1.65
3,AFG,1993,0.159,NaN,NaN,0.843,0.909,0.000,0.069,-1.65

### 1.1.2 Green house gas (GHG) Emissions Data

Load the `ghg.csv` file.

In [21]:
ghg_file_path = "../../data/hw/ghg.csv"
ghg = pd.read_csv(ghg_file_path)
ghg.tail(3)

            Country  year     emissions
11445  GLOBAL TOTAL  2021  51568.250032
11446  GLOBAL TOTAL  2022  51968.471601
11447  GLOBAL TOTAL  2023  52962.900859

## 1.2 Reading Data from an API

YOU MUST RUN THE NEXT CELL TO DOWNLOAD GDP AND POPULATION DATA

In [22]:
import requests
import io

def download_worldbank(indicator, countries, date_start, date_end):
    url_base = 'https://api.worldbank.org/v2/'
    country_codes = ';'.join(countries)
    url = f'{url_base}country/{country_codes}/indicator/{indicator}?date={date_start}:{date_end}&per_page=30000'
    response = requests.get(url)
    df = pd.read_xml(io.BytesIO(response.content))
    return df

### 1.2.1 Download GDP Data (1990-2026)

Download GDP per capita data for a different set of countries than those in the CSV files.

In [23]:
gdp_data = download_worldbank(
    indicator='NY.GDP.PCAP.CD',
    date_start= 1990,
    date_end= 2026,
    countries= ['GHA', 'ARE', 'IRN']
)
gdp_data.head(2)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
0,GDP per capita (current US$),United Arab Emirates,ARE,2025,NaN,NaN,NaN,1
1,GDP per capita (current US$),United Arab Emirates,ARE,2024,50273.506047,NaN,NaN,1

### 1.2.2 Download Population Data (1990-2026)

Download population data for the same countries.

In [24]:
population_indicator = 'SP.POP.TOTL'



country_list = [
    'GHA',  # Ghana
    'ARE',  # United Arab Emirates
    'IRN'   # Iran
]

pop_data = download_worldbank(
    indicator=population_indicator,
    countries=country_list,
    date_start=1990,
    date_end=2026
)
pop_data.tail(3)

,indicator,country,countryiso3code,date,value,unit,obs_status,decimal
105,"Population, total","Iran, Islamic Rep.",IRN,1992,61184983.0,NaN,NaN,0
106,"Population, total","Iran, Islamic Rep.",IRN,1991,59986931.0,NaN,NaN,0
107,"Population, total","Iran, Islamic Rep.",IRN,1990,58380092.0,NaN,NaN,0

# Section 2: Data Manipulation

Now let's practice the data manipulation techniques from Week 2.

## 2.1 Select Columns

Select specific columns from the democracy_gdp dataset.

In [10]:
democracy_gdp[['country', 'year', 'NGDPDPC']]

     country  year  NGDPDPC
0        AFG  1990      NaN
1        AFG  1991      NaN
2        AFG  1992      NaN
3        AFG  1993      NaN
4        AFG  1994      NaN
...      ...   ...      ...
5595     VNM  2020      NaN
5596     VNM  2021      NaN
5597     VNM  2022      NaN
5598     VNM  2023      NaN
5599     VNM  2024      NaN

[5600 rows x 3 columns]

## 2.2 Filter Rows

Filter rows based on conditions.

In [11]:
democracy_gdp['country'].unique()

array(['AFG', 'ARM', 'AZE', 'Asia (avg)', 'BGD', 'BTN', 'CHN', 'GEO',
       'HKG', 'IDN', 'IND', 'JPN', 'KAZ', 'KGZ', 'KHM', 'KOR', 'LAO',
       'LKA', 'MDV', 'MMR', 'MNG', 'MYS', 'NPL', 'PAK', 'PHL', 'PRK',
       'SGP', 'THA', 'TJK', 'TKM', 'TLS', 'TWN', 'UZB', 'VNM'],
      dtype=object)

In [12]:
democracy_gdp.query("country == 'JPN'")

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
385,JPN,1990,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
386,JPN,1991,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
387,JPN,1992,0.904,NaN,NaN,0.048,0.108,0.921,0.934,1.809
388,JPN,1993,0.905,NaN,NaN,0.048,0.108,0.921,0.934,1.809
389,JPN,1994,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
390,JPN,1995,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
391,JPN,1996,0.905,NaN,NaN,0.048,0.100,0.922,0.934,1.809
392,JPN,1997,0.906,NaN,NaN,0.048,0.100,0.921,0.934,1.809
393,JPN,1998,0.906,NaN,NaN,0.037,0.100,0.921,0.934,1.809
394,JPN,1999,0.906,NaN,NaN,0.037,0.100,0.921,0.934,1.809
395,JPN,2000,0.904,NaN,NaN,0.037,0.100,0.921,0.934,1.809
396,JPN,2001,0.902,NaN,NaN,0.037,0.100,0.920,0.934,1.809
397,JPN,2002,0.902,NaN,NaN,0.037,0.100,0.920,0.934,1.809
398,JPN,2003,0.902,NaN,NaN,0.037,0.100,0.921,0.934,1.809
399,JPN,2004,0.905,NaN,NaN,0.037,0.100,0.923,0.934,1.809
400,JPN,2005,0.906,NaN,NaN,0.037,0.100,0.927,0.934,1.809
401,JPN,2006,0.908,NaN,NaN,0.037,0.100,0.934,0.934,1.809
402,JPN,2007,0.908,NaN,NaN,0.037,0.100,0.934,0.934,1.809
403,JPN,2008,0.909,NaN,NaN,0.037,0.100,0.934,0.934,1.973
404,JPN,2009,0.915,NaN,NaN,0.037,0.100,0.934,0.938,1.973
405,JPN,2010,0.915,NaN,NaN,0.037,0.100,0.933,0.938,1.816
406,JPN,2011,0.915,NaN,NaN,0.037,0.100,0.933,0.938,1.816
407,JPN,2012,0.907,NaN,NaN,0.037,0.100,0.933,0.936,1.816
408,JPN,2013,0.909,NaN,NaN,0.037,0.100,0.931,0.883,1.816
409,JPN,2014,0.909,NaN,NaN,0.037,0.100,0.931,0.883,1.816
410,JPN,2015,0.911,NaN,NaN,0.037,0.078,0.931,0.883,1.816
411,JPN,2016,0.911,NaN,NaN,0.037,0.116,0.931,0.883,1.816
412,JPN,2017,0.911,NaN,NaN,0.037,0.107,0.933,0.883,1.816
413,JPN,2018,0.933,NaN,NaN,0.037,0.107,0.946,0.874,2.009
414,JPN,2019,0.930,NaN,NaN,0.037,0.107,0.946,0.871,2.009
415,JPN,2020,0.930,NaN,NaN,0.037,0.107,0.943,0.876,1.919
416,JPN,2021,0.929,NaN,NaN,0.037,0.094,0.943,0.859,1.919
417,JPN,2022,0.927,NaN,NaN,0.037,0.094,0.938,0.865,1.919
418,JPN,2023,0.927,NaN,NaN,0.037,0.092,0.938,0.866,1.919
419,JPN,2024,0.927,NaN,NaN,0.037,0.092,0.934,0.865,1.676

## 2.3 Multiple Conditions

Filter using multiple conditions.

In [13]:
democracy_gdp.query("country == 'KOR' and year == 2024").drop_duplicates()

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
2701,KOR,2024,0.817,36128.987,2.0,0.167,0.094,0.932,0.756,2.535

## 2.4 Filter in a List

Filter rows where column value is in a list.

In [14]:
democracy_gdp.query("country in ['JPN', 'KOR']")['country'].unique()

array(['JPN', 'KOR'], dtype=object)

## 2.5 Select Rows and Columns

Combine row filtering with column selection.

In [15]:
democracy_gdp.query("country == 'JPN' and year >= 2022")[['country', 'year', 'NGDPDPC', 'v2x_pubcorr']]

    country  year  NGDPDPC  v2x_pubcorr
417     JPN  2022      NaN        0.037
418     JPN  2023      NaN        0.037
419     JPN  2024      NaN        0.037

## 2.6 Rename Columns

Rename columns in the dataframe.

In [16]:
democracy_gdp.head(2)

,country,year,v2x_frassoc_thick,NGDPDPC,NGDP_RPCH,v2x_pubcorr,v2xnp_regcorr,v2xel_frefair,v2x_freexp,v2elembcap
0,AFG,1990,0.063,NaN,NaN,0.556,0.538,0.069,0.085,-1.65
1,AFG,1991,0.068,NaN,NaN,0.556,0.538,0.069,0.074,-1.65

In [17]:
democracy_gdp.rename({'year': 'date'}, axis=1)[['country', 'date']].head(2)

  country  date
0     AFG  1990
1     AFG  1991